server:
  port: 8081
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  sql.init.mode: always
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
  kafka:
    bootstrap-servers: rc1a-b5e65f36lm3an1d5.mdb.yandexcloud.net:9091
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties.spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.ByteArrayDeserializer

    jaas.enabled: true
    properties:
      security.protocol: SASL_SSL
      sasl:
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="9433_reader" password="eUIpgWu0PWTJaTrjhjQD3.hoyhntiK";
        mechanism: SCRAM-SHA-512
      ssl.truststore:
        location: "./.keystore"
        password: 111111

